---
version: "3.8"
services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: csevent
      POSTGRES_UESRNAME: postgres
      POSTGRES_PASSWORD: postgres